# Site
name: "LEVERJ"
title: "Leverj"
description: "The Non-custodial Leveraged Exchange."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-46278016-1'
disqus: 'leverj'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  bharath:
    name: bharath
    display_name: Bharath Rao
    gravatar: 632f1f3a5542ef31235ff44626848563
    email: bharath@leverj.io
    web: https://www.leverj.io
    twitter: https://twitter.com/bharathrao
    description: "Founder Leverj."
  nirmal:
    name: nirmal
    display_name: Nirmal Gupta
    gravatar: 027889cd98812550ce5e0a480f03068f
    email: nirmal@leverj.io
    web: https://www.leverj.io
    twitter: https://twitter.com/leverj_io
    description: "Co-Founder Leverj."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
